# Generated by Django 3.2.12 on 2022-03-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Taoyeucau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taoyeucau',
            name='Ngaygui',
            field=models.DateField(auto_now_add=True),
        ),
    ]
