# Generated by Django 3.2.4 on 2022-04-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamcong',
            fields=[
                ('ChamcongId', models.AutoField(primary_key=True, serialize=False)),
                ('NguoichamcongId', models.CharField(max_length=10)),
                ('Tennguoichamcong', models.CharField(max_length=10)),
                ('Thongtin', models.CharField(max_length=500)),
                ('Ngaycham', models.DateField()),
                ('Giobatdau', models.TimeField()),
                ('Gioketthuc', models.TimeField()),
            ],
        ),
    ]
