# Generated by Django 3.2.4 on 2022-04-06 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_ThemnhanVien', '0001_initial'),
        ('Main_Chamcong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaidatCamera',
            fields=[
                ('employees_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main_ThemnhanVien.employees')),
                ('Image', models.ImageField(null='False', upload_to='images')),
            ],
            bases=('Main_ThemnhanVien.employees',),
        ),
    ]
