# Generated by Django 3.2.4 on 2022-03-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('Date_of_birth', models.DateField()),
                ('PhoneNumber', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=50)),
                ('Address_Employee', models.CharField(max_length=1000)),
                ('Department', models.CharField(max_length=500)),
                ('Position_Employee', models.CharField(max_length=500)),
                ('Avatar', models.ImageField(null='False', upload_to='images')),
            ],
        ),
    ]
