# Generated by Django 3.2.4 on 2022-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_ThemnhanVien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Image',
            field=models.ImageField(null='True', upload_to='images'),
            preserve_default='True',
        ),
    ]
